#ifndef KORTOS_HAL_STM32F446XX_HAL_COMMON_H_
#define KORTOS_HAL_STM32F446XX_HAL_COMMON_H_

typedef enum
{
    KHAL_OK,
    KHAL_ERR_BUSY,
    KHAL_ERR_TIMEOUT,
    KHAL_ERR_TX,
    KHAL_ERR_RX,
    KHAL_ERR_INVALID_PARAM,
    KHAL_ERR_NULL_PTR
} KHAL_status_t;

#endif
